[character]
success_symbol = "[](light green) "
error_symbol = "[](red) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"
