#!/usr/bin/env sh
bookdir="/home/dnbias/Dropbox/Books/EBooks/"
# exrofi="rofi -theme $HOME/.repos/rofi-collection/minimal/minimal.rasi -i -lines 10 -dmenu -p Read"
exwofi="wofi -i -dmenu -M fuzzy -p Read:"

cd $bookdir || exit
chosen="$(ls {*.pdf,*.epub,*/*.pdf,*/*.epub} -R | $exwofi)"
zathura "$chosen" || exit
