#! /bin/sh

# Startups
$HOME/.config/polybar/launch-lev.sh &
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
ntfd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
promnesia serve &
dropbox &
easyeffects --gapplication-service &

# focus with pointer
bspc config focus_follows_pointer true

# Monitor setup
bspc config top_padding 16

# border colors basic
bspc config focused_border_color '#1f1f13'
bspc config normal_border_color '#0f0f17'

bspc monitor -d web emacs term misc media
# window gap and width
bspc config border_width         1
bspc config window_gap          14

# Defaults
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox-nightly state=tiled desktop='^1' follow=on
bspc rule -a firefox state=tiled desktop='^1' follow=on
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a Firefox desktop='^1' follow=on
bspc rule -a "YouTube Music" state=fullscreen desktop='^5'
bspc rule -a mplayer2 state=floating desktop='^5'
bspc rule -a Galculator state=floating
bspc rule -a kitty state=pseudo_tiled desktop='^3' follow=on
bspc rule -a URxvt state=pseudo_tiled desktop='^3' follow=on
bspc rule -a Emacs state=pseudo_tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#./borders &
